pub_cache:
  folder: ~/.pub-cache

task:
  container:
    dockerfile: .ci/Dockerfile
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
    - flutter channel master
    - flutter upgrade
    - git fetch origin master
    - pub global activate melos
  allow_failures: $CHANNEL == "master"
  matrix:
    - name: analyze
      env:
        matrix:
          CHANNEL: "master"
          CHANNEL: "stable"
      test_script: 
        - export PATH="$PATH":"$HOME/.pub-cache/bin"
        - flutter channel $CHANNEL
        - melos bootstrap
        - melos run lint:all
    - name: test
      env:
        CODECOV_TOKEN: ENCRYPTED[9ba9d1e58de2fc81556d89154383b44d9360408c6e7f40f5f7940d42b6c5bbac1cfb9c773ddcc20db6eba85622a3db38]
        matrix:
          CHANNEL: "master"
          CHANNEL: "stable"
      test_script:
        - export PATH="$PATH":"$HOME/.pub-cache/bin"
        - flutter channel $CHANNEL
        - melos bootstrap
        - melos run lint:all
        - cd packages/location
        - if [ $CHANNEL = "stable" ]; then bash <(curl -s https://codecov.io/bash); fi
        - cd ../location_platform_interface
        - if [ $CHANNEL = "stable" ]; then bash <(curl -s https://codecov.io/bash); fi


